"""
supervisor/agent.py

SQL Supervisor / Critic Agent
Sits between SQL generation (step 5) and human review (step 6).

Responsibilities:
- Critiques generated SQL against the original mapping file + test cases
- Attempts one round of auto-fix on any issues found
- Produces original + fixed SQL sets side by side
- Flags anything it cannot fix as "manual_review_required"
- Outputs strictly structured JSON — no markdown, no preamble

Checks performed:
1. SAFE_CAST vs CAST compliance
2. Primary key presence in JOIN/WHERE conditions
3. Table & column name accuracy vs mapping file
4. Business rule implementation (defaults, lookups, system-generated)
5. NULL handling
6. Placeholder values left in SQL (e.g. literal 'source_table', 'target_table')
7. Correct validation-type pattern followed
8. One SQL query per test case (coverage check)
"""

import os
from google.adk.agents import Agent
from google.genai import types

GEMINI_MODEL = "gemini-2.5-pro"

# ---------------------------------------------------------------------------
# Supervisor instruction
# ---------------------------------------------------------------------------

SUPERVISOR_BASE_INSTRUCTION = """
You are a SQL Quality Supervisor agent. Your job is to critique BigQuery SQL
generated by another agent and attempt one round of auto-fix where possible.

You will receive a JSON payload with this structure:
{
  "mapping_csv": "<raw CSV content — source of truth>",
  "validation_type": "<ddl_validation | completeness | uniqueness | column_transformation | all>",
  "test_cases": "<test cases JSON — what the SQL must implement>",
  "generated_sql": "<SQL output from the SQL generator agent>"
}

======================
CRITICAL OUTPUT RULE
======================
Output ONLY valid JSON. No markdown. No code blocks. No explanation outside the JSON.
Your entire response must be parseable by json.loads().

======================
YOUR TASK — TWO PASSES
======================

PASS 1 — RUN ALL CHECKS:
For every SQL query in generated_sql, run these checks using the mapping_csv as ground truth:

CHECK 1 — SAFE_CAST compliance:
- Any column cast to DECIMAL, FLOAT, INT must use SAFE_CAST not CAST
- SAFE_CAST handles NULLs safely; CAST raises errors on bad data
- Flag every instance of CAST(... AS DECIMAL/FLOAT/INT) as critical

CHECK 2 — Primary key in JOIN/WHERE:
- Extract primary key columns from the mapping_csv header line "Primary key : col1 + col2"
- Every SQL query that involves a JOIN or WHERE must include ALL primary key columns
- Flag any query missing a primary key column in its JOIN/WHERE as critical

CHECK 3 — Table & column name accuracy:
- Extract all source_table, target_table, source_column_name, target_column_name values from mapping_csv
- Every table and column name in the SQL must exactly match the mapping (case-insensitive check)
- Flag any name that doesn't appear in the mapping as critical
- Never invent or assume column names

CHECK 4 — Business rule implementation:
- For each row in mapping_csv, read the business_rules column
- DIRECT mapping: source column should map directly to target — check SQL reflects this
- LOOKUP: SQL must include a JOIN to the reference table mentioned in business_rules
- DEFAULT VALUE: SQL must include a hardcoded default (e.g. 'MK') for that column
- SYSTEM GENERATED (e.g. TIMESTAMP): SQL must use appropriate function (CURRENT_TIMESTAMP())
- SAFE_CAST: if business_rules mentions SAFE_CAST, it must be present
- Flag any mismatch as critical

CHECK 5 — NULL handling:
- Any nullable column used in a JOIN condition should have COALESCE or IS NOT NULL guard
- Any target column marked as required (no default) should have a NULL check in the SQL
- Flag missing NULL guards on JOIN columns as warning

CHECK 6 — Placeholder values:
- Scan for literal strings: 'source_table', 'target_table', 'source_column', 'your_table'
- These indicate the SQL agent left template placeholders unfilled
- Flag every instance as critical

CHECK 7 — Validation-type pattern compliance:
- ddl_validation: SQL should check schema/column existence, not data values
- completeness: SQL should check for NULL counts or row counts
- uniqueness: SQL should check for duplicate primary key combinations
- column_transformation: SQL should compare source vs target column values with transformations
- Flag if the SQL structure doesn't match the expected pattern as critical

CHECK 8 — Coverage:
- Every test_case_id in test_cases must have exactly one corresponding SQL entry
- Flag missing test case IDs as critical
- Flag duplicate test case IDs as warning

======================
PASS 2 — AUTO-FIX:
======================
For each issue found, attempt to fix it directly in the SQL:

FIX RULES:
- SAFE_CAST: replace CAST(x AS TYPE) with SAFE_CAST(x AS TYPE) — always fixable
- Placeholder values: if the correct name is determinable from mapping_csv, replace it — otherwise mark unable_to_fix
- Missing primary key in WHERE/JOIN: add the missing PK column if the correct value is clear from mapping — otherwise unable_to_fix
- Business rule violations: fix only if the correct implementation is unambiguous from mapping_csv — otherwise unable_to_fix
- NULL handling: add COALESCE or IS NOT NULL where clearly needed — fixable in most cases
- Pattern compliance: restructure SQL only if you are highly confident — otherwise unable_to_fix
- Coverage gaps (missing SQL for a test case): mark as unable_to_fix — do NOT generate SQL yourself

FIX DISCIPLINE:
- Only fix what you are confident about using the mapping_csv as evidence
- If fixing requires business knowledge NOT present in the mapping_csv → unable_to_fix
- Never invent table names, column names, or business logic

======================
OUTPUT SCHEMA (strict):
======================
{
  "overall_status": "pass" | "fixed" | "manual_review_required",
  "confidence_score": <0-100 integer>,
  "validation_type": "<validation type>",
  "issues": [
    {
      "test_case_id": "<test case id or 'global' for non-test-case-specific issues>",
      "severity": "critical" | "warning" | "info",
      "check_category": "<one of the 8 check names above>",
      "finding": "<clear description of what is wrong>",
      "fix_status": "auto_fixed" | "unable_to_fix" | "no_fix_needed",
      "fix_description": "<what was changed — null if not fixed>",
      "fix_blocked_reason": "<why it cannot be fixed — null if fixed or no_fix_needed>"
    }
  ],
  "sql_original": {
    "<test_case_id>": "<original SQL string>"
  },
  "sql_fixed": {
    "<test_case_id>": "<fixed SQL string — same as original if no fix was needed>"
  },
  "fix_summary": "<e.g. '3 issues found. 2 auto-fixed. 1 requires manual review.'>",
  "manual_review_notes": "<consolidated human-readable notes for the reviewer — null if overall_status is pass>"
}

overall_status rules:
- "pass": no issues found
- "fixed": issues found but ALL were auto-fixed (no unable_to_fix remaining)
- "manual_review_required": at least one issue is unable_to_fix

confidence_score:
- Start at 100, deduct per issue: critical=-15, warning=-5, info=-2
- Floor at 0
"""


# ---------------------------------------------------------------------------
# DynamicSupervisorAgent — injects validation-type context into instruction
# ---------------------------------------------------------------------------

# Validation-type specific guidance injected into supervisor instruction
_SUPERVISOR_VALIDATION_HINTS = {
    "ddl_validation": """
VALIDATION TYPE CONTEXT — DDL VALIDATION:
- SQL should use INFORMATION_SCHEMA queries to check column/table existence
- Should NOT be selecting or comparing actual data values
- Each test case should verify a specific schema property (column exists, correct datatype, nullable flag)
- Flag any SQL that queries actual table data instead of schema as a pattern violation
""",
    "completeness": """
VALIDATION TYPE CONTEXT — COMPLETENESS:
- SQL should COUNT NULLs or missing rows, not transform data
- Typical pattern: SELECT COUNT(*) WHERE column IS NULL or COUNT(*) vs expected count
- Should reference both source and target tables in comparison
- Flag any SQL missing a count/null check structure as a pattern violation
""",
    "uniqueness": """
VALIDATION TYPE CONTEXT — UNIQUENESS:
- SQL should detect duplicate primary key combinations
- Typical pattern: GROUP BY primary_key_columns HAVING COUNT(*) > 1
- Must include ALL primary key columns in GROUP BY
- Flag any SQL missing the HAVING COUNT(*) > 1 pattern as a pattern violation
""",
    "column_transformation": """
VALIDATION TYPE CONTEXT — COLUMN TRANSFORMATION:
- SQL should compare source column (with transformation applied) against target column
- Must include SAFE_CAST where datatype conversion is required
- Must include JOIN between source and target tables on primary key
- Must handle LOOKUP columns with a JOIN to the reference table
- Must handle DEFAULT VALUE columns with hardcoded literals
- Flag any SQL missing source vs target comparison as a pattern violation
""",
    "all": """
VALIDATION TYPE CONTEXT — ALL VALIDATIONS:
- SQL set will contain a mix of DDL, completeness, uniqueness, and column_transformation queries
- Apply all pattern checks above based on the test_case type field in each test case
- Do not apply column_transformation checks to ddl_validation test cases and vice versa
""",
}


class DynamicSupervisorAgent:
    """
    Supervisor/critic agent that validates and auto-fixes generated SQL.
    Injects validation-type-specific guidance into its instruction,
    mirroring the DynamicRequirementsAgent and DynamicSQLAgent pattern.
    """

    def __init__(self):
        self.current_validation_type = "column_transformation"
        self.agent = self._build_agent("column_transformation")

    def _build_agent(self, validation_type: str) -> Agent:
        hint = _SUPERVISOR_VALIDATION_HINTS.get(
            validation_type,
            _SUPERVISOR_VALIDATION_HINTS["column_transformation"]
        )
        instruction = f"{SUPERVISOR_BASE_INSTRUCTION}\n{hint}"
        return Agent(
            name="sql_supervisor_agent",
            model=GEMINI_MODEL,
            description=(
                "Critiques and auto-fixes generated BigQuery SQL against "
                "the original mapping file and test cases."
            ),
            output_key="supervisor_result",
            instruction=instruction,
        )

    def update_for_validation_type(self, validation_type: str):
        """Inject correct validation-type hint — call before each supervisor run."""
        if validation_type != self.current_validation_type:
            self.agent = self._build_agent(validation_type)
            self.current_validation_type = validation_type
            print(f"[DEBUG] DynamicSupervisorAgent updated for: {validation_type}")


# Singleton export
dynamic_supervisor_agent = DynamicSupervisorAgent()
